name: PCI-NKO
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - python-dotenv
  - python-dateutil
  - pandas
  - plotly
  - optuna
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - spacy
  - tqdm
  - pip
  - pip:
    - evaluate
    - openai
    - langchain
    - sentence-transformers
    - python-docx
    # Add any additional pip packages if necessary